import Head from "next/head";
import { gql, GraphQLClient } from "graphql-request";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import PostCard from "@/Components/Card";

export async function getServerSideProps() {
  const url = "https://gapi.storyblok.com/v1/api";

  const client = new GraphQLClient(url, {
    headers: {
      token: process.env.PublicToken,
      version: "published",
    },
  });

  const query = gql`
    {
      BlogpostItems {
        items {
          id
          name
          slug
          content {
            Featured_Image {
              filename
              alt
            }
            Author {
              name
              content
            }
          }
        }
      }
    }
  `;

  const { BlogpostItems } = await client.request(query);
  return { props: { data: BlogpostItems.items } };
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.itemContainer}>
          {data.map(({ id, name, slug, content }) => {
            return (
              <div key={id}>
                <PostCard title={name} content={content} slug={slug} id={id}/>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}
